#!/bin/bash
#if [ ! -d "commons-cli-1\.[3-5]\.\d" ]
if [ ! -d "commons-cli-1.5.0" ]
then
    wget https://commons.apache.org/cli/download_cli.cgi
    tar -xvf commons-cli-1.*
fi

#javac -cp commons-cli-1.5.0/commons-cli-1.5.0.jar: MostActiveCookie.java
qct_home=$(pwd)
#export CLASSPATH=$CLASSPATH:$qct_home/commons-cli-1.5.0/commons-cli-1.5.0.jar:$qct_home/JUnit/junit4.10/junit-4.10.jar:$qct_home
export CLASSPATH=$CLASSPATH:$qct_home/commons-cli-1.5.0/commons-cli-1.5.0.jar:$qct_home
javac *.java
#exec java -cp commons-cli-1.5.0/commons-cli-1.5.0.jar: MostActiveCookie "$@"
exec java MostActiveCookie "$@"
