#!/bin/bash
if [ ! -d "commons-cli-1.5.0" ]
then
    wget https://commons.apache.org/cli/download_cli.cgi
    tar -xvf commons-cli-1.*
fi

qct_home=$(pwd)
export CLASSPATH=$CLASSPATH:$qct_home/commons-cli-1.5.0/commons-cli-1.5.0.jar:$qct_home
javac MostActiveCookie.java LogMap.java
exec java MostActiveCookie "$@"
