#!/bin/bash
if [ ! -d "commons-cli-1.5.0" ]
then
    wget https://commons.apache.org/cli/download_cli.cgi
    tar -xvf commons-cli-1.*
fi
if [ ! -d "JUnit" ]
then
    mkdir JUnit
fi
if [ ! -d "JUnit/junit4.10" ]
then
    wget https://sourceforge.net/projects/junit/files/junit/4.10/junit4.10.zip -P JUnit
    unzip JUnit/junit4.10.zip -d JUnit/
fi

qct_home=$(pwd)
export CLASSPATH=$CLASSPATH:$qct_home/commons-cli-1.5.0/commons-cli-1.5.0.jar:$qct_home/JUnit/junit4.10/junit-4.10.jar:$qct_home
javac *.java
exec java LogMapTest
